### ISSUE TITLE
KeyError in assigning t_id to seed word topics

### ISSUE THREAD

**Issue by sonamgupta1105** [dex314/GuidedLDA_WorkAround#2]
Any suggestions how to fix this error ?

`Traceback (most recent call last):
  File "/guidedlda.py", line 27, in <module>
    seed_topics[word2id[word]] = t_id
KeyError: 'player'`

**Comment by dex314** [comment]
Hi! It looks like someone forked the original and possibly fixed many of the previous issues:
https://github.com/vi3k6i5/GuidedLDA/pull/56

Let me know if their fork helps you out.

**Comment by sonamgupta1105** [comment]
@dex314 I tried the update you shared using that link. I updated the setup.py and tried installing using pip install GuidedLDA but kept giving me error (Command errored out with exit status 1). I am using Windows 10, Python 3.7 . After that I tried git clone and tried to run python setup.py just to see if it helps but it did not. I have attached a screenshot of the error. Do you have any suggestions to fix it?
![image](https://user-images.githubusercontent.com/8378764/110978667-aaf8cb80-8331-11eb-91ef-38ab51748c6c.png)

**Comment by dex314** [comment]
Did you try installing LDA first like I mention in the read me of the work around? For example, ``pip install lda`` ? And then dropping the work around files in?

When I take a look at the latest lda documentation https://lda.readthedocs.io/en/latest/installation.html , it appears there are limitations on operating systems and I currently cant test this out to make sure it still works.

**Comment by sonamgupta1105** [comment]
@dex314 For workaround, I followed the instructions from README as is. Then the keyerror occurred. I used the forked repo to install original guidedLDA package because I thought that would resolve the KeyError since it was updated. KeyError still persists using the forked version of original guidedLDA. Does this make sense?

**Comment by dex314** [comment]
Sort of, as I mentioned I cant really test this at the moment, but according to your the email notification I got about your first post it looks like you put guidedlda.py in the wrong place:

Traceback (most recent call last): File "d:/.../DATA/guidedlda.py", line 27, in <module> seed_topics[word2id[word]] = t_id KeyError: 'player'

That doesnt look right. guidedlda.py and the other files in this repo should be in your package environment, for example, if youre using Anaconda it might look like: C:\users\<username>\apps\anaconda3\lib\site-packages\lda
Or wherever your python environment packages lie.

It needs to be in the lda folder with lda.py.

Let me know if this works.

**Comment by sonamgupta1105** [comment]
@dex314 Yes I double checked and the files seem to be at this directory path same as lda.py "\Anaconda3\Lib\site-packages\lda"

I'll try to reinstall and start again from the beginning.
